### PR TITLE
provide quantum security in qubits

### PR DESCRIPTION
**Pull request by kriskwiatkowski**
In case of quantum security, let's provide it in qubits as described in [SIKE]

### CODE REVIEW

**Comment by franziskuskiefer** [comment]
Can you add a sentence how qubits are defined or maybe a reference? Not everyone might know.

**Comment by kriskwiatkowski** [comment]
How about adding this paper, I find it OK, do you think it will do?
https://arxiv.org/pdf/1706.06752.pdf

**Comment by kriskwiatkowski** [comment]
BTW: those numbers are taken from http://sike.org/files/SIDH-spec.pdf table 5.1.
In fact there is another paper which challenges those numbers, but I would prefer to stay closer to what was submitted to NIST

**Comment by franziskuskiefer** [comment]
>  https://arxiv.org/pdf/1706.06752.pdf

yeah that should do.

>  In fact there is another paper which challenges those numbers, but I would prefer to stay closer to what was submitted to NIST

I'd mention that these are the numbers from the NIST submission to make clear that's not something we came up with and that there might be other numbers.

**Comment by kriskwiatkowski** [comment]
Ok, done. It is mention line above the table, that those numbers come from {{SIKE}}. Which wasn't true and actually not something I want to do, hence the change.

**Pull request merged**
